name: PR gate workflow
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  pr-gate:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Configure Linux
        run: echo 16384 | sudo tee /proc/sys/fs/inotify/max_user_watches
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@vertexinc'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PACKAGE_TOKEN }}
      - id: install-dependencies
        name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Install dependencies (failure)
        if: failure() && steps.install-dependencies.outcome == 'failure'
        run: echo 'If a @vertexinc-scoped package failed to install, please ensure that the SystemTeamAutomation GitHub user has access to the repository that failed to install.  The GIT_PACKAGE_TOKEN secret (which is necessary to authorize the `npm install` command) is owned by that account and is only available to repos that that account has access to.'
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test
      - name: Build
        run: npm run build:${{ env.NODE_ENV }}
      - id: cypress-mocked-api-tests
        name: Cypress mocked-api tests
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'https://localhost:9001/${{ github.event.repository.name }}.js'
          start: npm run start:${{ env.NODE_ENV }}
          command: npm run cypress:run:${{ env.NODE_ENV }}
          install: false
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
      - name: Cypress mocked-api tests (failure)
        if: failure() && steps.cypress-mocked-api-tests.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: cypress-mocked-api-artifacts
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 1
      - name: Stop running app
        run: |
          echo 'Killing all processes, including webpack-devserver, so the app can be restarted on the same port'
          killall node
      - id: cypress-e2e-tests
        name: Cypress end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'https://localhost:9001/${{ github.event.repository.name }}.js'
          start: npm run start:${{ env.NODE_ENV }}
          command: npm run cypress:run:e2e:${{ env.NODE_ENV }}
          install: false
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
      - name: Cypress end-to-end tests (failure)
        if: failure() && steps.cypress-e2e-tests.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: cypress-e2e-artifacts
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 1
